### ISSUE TITLE
Controllers & base stations are only rendered in the left eye

### ISSUE THREAD

**Issue by markasselin** [KitwareMedical/SlicerOpenVR#6]
Left Eye
![left-eye](https://user-images.githubusercontent.com/17535566/33778191-a2b991a0-dc15-11e7-9557-0507605770b8.PNG)

Right Eye
![right-eye](https://user-images.githubusercontent.com/17535566/33778192-a2caf3e6-dc15-11e7-9c1e-e2d688b0048d.PNG)

**Comment by jbvimort** [comment]
Hello Mark!

Thanks for your interest in SlicerVR!

We actually encountered the same issue, it has been identified and addressed with this [hack ](https://github.com/jbvimort/Slicer/commit/4fab097ec7ed88958046cb568453a69071b86034) on Slicer.

Since it still hasn't been integrated to Slicer. For now cherry-picking this single commit and recompiling Slicer should solve the issue.

Tell me if it's not working!

**Comment by markasselin** [comment]
@jbvimort Thanks for passing along the hack, I appreciate it. I will let you know if I have any problems with it.

**Comment by jcfr** [comment]
Since this addressed the problem, I am not closing this issue.
